### ISSUE TITLE
ABAP cleaner has encountered a problem: For input string: "fallback"

### ISSUE THREAD

**Issue by SmogulT** [SAP/abap-cleaner#21]
Hello,

thank you for the tool. It is great, we all installed it on our Eclipse :)

We are encountering on SAP systems with SAP_BASIS release 750 an error. On 756 and 757 it is working fine.

```
eclipse.buildId=4.24.0.I20220607-0700
java.version=11.0.11
java.vendor=Red Hat, Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64

com.sap.adt.abapcleaner.gui
Error
Wed May 24 11:07:37 CEST 2023
ABAP cleaner has encountered a problem

java.lang.NumberFormatException: For input string: "fallback"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.sap.adt.abapcleaner.rulebase.Rule.isCleanupAllowedFor(Rule.java:374)
	at com.sap.adt.abapcleaner.rulebase.Rule.executeIfAllowedOn(Rule.java:355)
	at com.sap.adt.abapcleaner.rulebase.Profile.executeRules(Profile.java:198)
	at com.sap.adt.abapcleaner.programbase.Task.run(Task.java:168)
	at com.sap.adt.abapcleaner.programbase.Task.run(Task.java:120)
	at com.sap.adt.abapcleaner.programbase.Job.runSingleCodeDocument(Job.java:109)
	at com.sap.adt.abapcleaner.programbase.Job.run(Job.java:98)
	at com.sap.adt.abapcleaner.gui.FrmMain$50.run(FrmMain.java:1311)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at com.sap.adt.abapcleaner.gui.FrmMain.runJobWithProgressUiIfNeeded(FrmMain.java:1308)
	at com.sap.adt.abapcleaner.gui.FrmMain.runJobWithProgressUiIfNeeded(FrmMain.java:1300)
	at com.sap.adt.abapcleaner.gui.FrmMain.refreshCode(FrmMain.java:1259)
	at com.sap.adt.abapcleaner.gui.FrmMain.open(FrmMain.java:345)
	at com.sap.adt.abapcleaner.gui.FrmMain.cleanInteractively(FrmMain.java:265)
	at com.sap.adt.abapcleaner.gui.eclipse.AbapCleanerHandlerBase.execute(AbapCleanerHandlerBase.java:96)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
 
```

Best regards,
Tim

**Comment by jmgrassau** [comment]
Hi Tim, 

thanks for reporting this – the call stack actually tells the whole story. We expect a string with the ABAP release version here (e.g. "757"), but apparently that is not available in all cases, and then seems to default to the string "fallback". So, in such cases, ABAP cleaner shall probably assume a lower release, turning off newer features such as the calculation assignment operators += etc. Will fix this asap!

> thank you for the tool. It is great, we all installed it on our Eclipse :)

Very happy to hear that, thank you! 

Kind regards
Jörg-Michael

**Comment by jmgrassau** [comment]
Hi Tim, 

this issue should now be resolved in the new ABAP cleaner release (version 1.2.1), so ABAP cleaner should then work in the system with SAP_BASIS release 7.50 as well, automatically skipping cleanup rules that would introduce newer syntax, namely 

* "Replace RAISE ... TYPE with RAISE ... NEW" (7.52 or higher), 
* "Prefer calculation assignment operators (+=, -= etc.)" (7.54),
* "Use FINAL for immutable variables" (7.57), and even 
* "Replace obsolete pseudo comments with pragmas" (7.02) – this one is skipped, too, because from the string "fallback", ABAP cleaner can't tell the release 7.50. 

Please let me know if there are further issues! 

Kind regards,
Jörg-Michael
